@echo off 
echo MEMULAI SISTEM... 
echo 1. Radar System... 
python radar_distance.py 
echo 2. Drone Controller...   
python drone.py 
echo 3. Alert System... 
python alert_system.py 
echo 4. Web Server... 
python server.py 
echo 5. Buka Dashboard... 
start dashboard.html 
echo. 
echo SISTEM BERJALAN! 
echo Akses: http://localhost:9090 
pause 
